on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x 
    - name: Test
      run: dotnet test -t ./src

